name: sync_datetime
description: Dart & Flutter DateTime utilities for UTC timezone conversion, ISO 8601 parsing, client-server synchronization, REST API timestamps, date calculations, and calendar math.
version: 0.1.5
repository: https://github.com/rahimuj570/sync_datetime

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
